# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vector_search_pb2 as vector__search__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorSearchStub(object):
    """Minimal gRPC protocol for a dedicated vector-search pool.
    Data-plane (e.g., Mooncake RDMA) will be added in later PRs.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/sglang.grpc.vector_search.VectorSearch/Search',
                request_serializer=vector__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__search__pb2.SearchResponse.FromString,
                _registered_method=True)


class VectorSearchServicer(object):
    """Minimal gRPC protocol for a dedicated vector-search pool.
    Data-plane (e.g., Mooncake RDMA) will be added in later PRs.

    """

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vector__search__pb2.SearchRequest.FromString,
                    response_serializer=vector__search__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sglang.grpc.vector_search.VectorSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sglang.grpc.vector_search.VectorSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorSearch(object):
    """Minimal gRPC protocol for a dedicated vector-search pool.
    Data-plane (e.g., Mooncake RDMA) will be added in later PRs.

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sglang.grpc.vector_search.VectorSearch/Search',
            vector__search__pb2.SearchRequest.SerializeToString,
            vector__search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
